project_id = "vnmwvrjuowmdvjhyuebm"

[functions.frogapi-balance]
verify_jwt = true

[functions.frogapi-send-general]
verify_jwt = true

[functions.frogapi-send-personalized]
verify_jwt = true

[functions.frogapi-history]
verify_jwt = true

[functions.frogapi-otp-generate]
verify_jwt = false

[functions.frogapi-otp-verify]
verify_jwt = false

[functions.system-otp-verify]
verify_jwt = false

[functions.frogapi-test-otp]
verify_jwt = false

[functions.approve-applicant]
verify_jwt = true

[functions.check-approval]
verify_jwt = false