project_id = "vnmwvrjuowmdvjhyuebm"

[functions.frogapi-balance]
verify_jwt = true

[functions.frogapi-send-general]
verify_jwt = true

[functions.frogapi-send-personalized]
verify_jwt = true

[functions.frogapi-history]
verify_jwt = true